### ISSUE TITLE
Add youtube link to the footer of the webpages.

### ISSUE THREAD

**Issue by shadowman** [codurance/site#1514]
As described in the title.

The link is this: https://www.youtube.com/user/codurance

**Comment by shadowman** [comment]
@anguspaterson I don't know if you have this on your backlog.

**Comment by keith-smale** [comment]
I already made some changes for this, although the stock icon we have for YouTube is not that great.
https://github.com/codurance/site/pull/1508

**Comment by sherlockq** [comment]
IMO the whole footer region should be redesigned otherwise few people would notice those tiny icons. It took me quite a while to find them even I know it should be somewhere.

Yet just regarding this PR I think it's ready to be deployed. Once @anguspaterson finishs the design we can have another ticket for them.

Shall I do that? @keith-smale

**Comment by josewenzel** [comment]
BTW I already did this Nicholle asked for it last week, @sherlockq I believe that there are working on a redesign for the whole website

**Comment by sherlockq** [comment]
> BTW I already did this Nicholle asked for it last week, @sherlockq I believe that there are working on a redesign for the whole website

Yeah I understand. But actually those two tasks should be blocking each other. By the standard of current design, this PR is ready to go.

**Comment by josewenzel** [comment]
This is done by the way
