### ISSUE TITLE
Cannot access article in the site preview

### ISSUE THREAD

**Issue by cyplo** [codurance/site#545]
https://site-remove-author-twitter.s3-eu-west-1.amazonaws.com/2017/01/16/hierarchy-of-opinion/

gives me 
![image](https://cloud.githubusercontent.com/assets/217899/22213540/7bb78adc-e18c-11e6-95c2-58ca05897c82.png)

**Comment by PaNaVTEC** [comment]
The problem seems to be something related with the configuration of the bucket. if you click in this link instead: [https://site-remove-author-twitter.s3-eu-west-1.amazonaws.com/2017/01/16/hierarchy-of-opinion/index.html](https://site-remove-author-twitter.s3-eu-west-1.amazonaws.com/2017/01/16/hierarchy-of-opinion/index.html) it works.
Since we are trying to move towards the approach of having one bucket instead of creating one per pr, I will deffinitly address this, but after addressing this issue: https://github.com/codurance/site/issues/512

**Comment by PaNaVTEC** [comment]
This is already fixed, the problem was that we dind't have a root index.html in the bucket. After putting a random index.html in the root of the site-pr bucket it started to work.

**Comment by cyplo** [comment]
I think that for Sandro's recent PR, when I clicked around I got the access denied XML message again.

**Comment by PaNaVTEC** [comment]
Weird, I've seen it working when @mashooq created an index.html in the root of the bucket.

**Comment by cyplo** [comment]
Maybe it would be worth it to write a simple automated check for that, e.g. using curl, that would run after deployment ?

**Comment by lpalma** [comment]
Is this issue still relevant? I haven't heard of/had problems visualizing the site preview so far.

**Comment by PaNaVTEC** [comment]
I think is already fixed
